### ISSUE TITLE
Default window size (and possibly position) no longer work on Windows (maybe others)

### ISSUE THREAD

**Issue by MikeYeager** [tryphotino/photino.Native#126]
.SetUseOsDefaultSize(true) (or simply omitting it) creates a minimal window with only resize and close controls visible (height = 0, width = 0) instead of using Windows defaults. Have not tested default position or tested on Mac or Linux.

**Comment by IceReaper** [comment]
We have identical issues with MinSize and Fullscreen. It starts to become a mess... Currently thinking about implementing our own library instead of photino, as the app is pretty close to launch, and photino window properties are not working consistently.
examples:
- set a minsize works, but it always returns 0,0.
- fullscreen api works only once. Afterwards its always set to false and ignoring setting it to true.

**Comment by MikeYeager** [comment]
Several issues arose in .NET 7 and above when we changed marshalling from DllImport attributes to LibraryImport attributes in order to support AOT compilation. .NET 6 was not affected. Boolean and String marshalling have both been fixed on all platforms in the upcoming release.
