### ISSUE TITLE
Need to be able pass in the "UserData Folder" to prevent access denied messages

### ISSUE THREAD

**Issue by Smurf-IV** [tryphotino/photino.Native#58]
If the Tes application is installed into %ProgramFolders%, then it cannot run due to the "UsedDataFolder" of WebView being created in a subdirectory.

Even running as Administrator does not solve the problem.

**Comment by Smurf-IV** [comment]
NO.. not the "MyDocuments" folder, because some institutions have this linked to always backup to a shared drive (Like one drive etc)
What's wrong with ProgramData ? (Or it's equivalent on Mac and Linux!)

**Comment by MikeYeager** [comment]
@Smurf-IV While the conversations I've seen favor the MyDocuments folder, I don't see any reason we can't use the AppData folder for the user instead. Perhaps we can allow developers to override this when creating new windows as well.

**Comment by dimi3tron** [comment]
The user's AppData directory is the standard for application data. Why would you want to change it to MyDocuments? That's so arbitrary. 
Most users don't want to see bunch of temporary or configuration files from some rando app cluttering up their Documents directory. Also, this directory usually syncs with onedrive, and not many use cases need your app's data synced with the user's cloud storage.

My two cents...

**Comment by MikeYeager** [comment]
@dimi3tron Thanks for the feedback. There is now a mechanism for setting the folder in the next upcoming version. It now defaults to the same folder as the .exe unless it's specifically set, but the default could easily be changed to the user's AppData folder now that the code is in place.

**Comment by dimi3tron** [comment]
That is a workable solution.

I'm just going to hammer on it one last time, because I'm a firm believer that sensible defaults and adherence to standards and conventions make our lives as developers a lot easier. 

This means that I'd want to install my app in a conventional place. This would be one of the Program Files directories on windows. In common setups, users won't have the necessary rights to write to these directories. So why not just default it to the AppData dir? I understand I'm nitpicking  and this is a cross-platform solution, so there will different configurations needed for each platform. 

However, when I use a framework I expect it to use sensible defaults, so I don't have to worry about those things and I can just focus on the application I'm building. I don't have the slightest clue where I'd have to write user data on a Mac. I expect this sort of thing to be taken care of b the framework devs.

*Drops mic*

I'm just kind of ranting here, but I hope you can find some value in my remarks. I'll let it rest now  :-)

Or fork it and create a PR.

**Comment by MikeYeager** [comment]
@dimi3tron This has already been implemented in 2.0! On Windows, it will default to AppDataLocal. It can also be overridden on any platform to any path you like. We're currently testing on Linux and then macOS before releasing.
